image: jakzal/phpqa:php8.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
before_script:
    - docker compose up -d
    - docker exec -it app_php bash
    - composer install

cache:
    paths:
        - app/vendor/

stages:
    - SecurityChecker
    - CodingStandards
    - UnitTests

security-checker:
    stage: SecurityChecker
    script:
        - security-checker security:check app/composer.lock
    allow_failure: false

phpcs:
    stage: CodingStandards
    script:
        - phpcs -v --standard=PSR2 --ignore=./app/src/KERNEL.php ./app/src
    allow_failure: false

phpstan:
    stage: CodingStandards
    script:
        - phpstan analyse ./app/src
    allow_failure: false

twig-lint:
    stage: CodingStandards
    script:
        - twig-lint lint ./app/templates
    allow_failure: false

phpunit:
    stage: UnitTests
    script:
        - php bin/phpunit
    allow_failure: false