name: Php Composer

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install composer
              run: composer install

            - name: Run phpstan
              run: ./vendor/bin/phpstan analyse src --level 5

            - name: php unit
              run: ./bin/phpunit